markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!--break-->"

github: CodeToSurvive
author: "CodeToSurvive"
email: 2305886442#qq.com
name: "CodeToSurvive的个人博客"
url: https://codetosurvive1.github.io
domain: CodeToSurvive1.github.io
all_categories: [
["hadoop", "hadoop","/posts/hadoop.html"],
["spark", "spark","/posts/spark.html"],
["hbase", "hbase","/posts/hbase.html"],
["hive", "hive","/posts/hive.html"],
["macaca", "macaca","/posts/macaca.html"],
["read", "读书笔记","/posts/read.html"],
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
# timezone: America/Los_Angeles
timezone: Asia/Shanghai

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
